language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install valgrind
  - sudo apt-get install libev-dev
  - sudo apt-get install libasound2-dev
  - sudo apt-get install libx264-dev
  - sudo apt-get install yasm
  - sudo apt-get install libc6-i386
  - sudo apt-get remove libqtwebkit-dev

  # bitstream
  - git clone --depth 1 git://git.videolan.org/bitstream.git
  - sudo make -C bitstream install

  # ffmpeg
  - curl http://ffmpeg.org/releases/ffmpeg-2.7.1.tar.bz2 | tar -xj
  - cd ffmpeg-2.7.1
  - ./configure
    --enable-shared
    --disable-all
    --disable-doc
    --disable-libxcb
    --disable-sdl
    --disable-xlib
    --disable-iconv
    --enable-avutil
    --enable-avformat
    --enable-avcodec
    --enable-swscale
    --enable-swresample
    --enable-encoder=mpeg2video
    --enable-encoder=mp2
  - sudo make install
  - cd ..

  # nacl sdk
  - wget http://storage.googleapis.com/nativeclient-mirror/nacl/nacl_sdk/nacl_sdk.zip
  - unzip nacl_sdk.zip
  - nacl_sdk/naclsdk update pepper_43

  # libamt
  - git clone --depth 1 https://github.com/cisco/SSMAMTtools.git
  - make CFLAGS='$(ADD_INCLUDE_DIR) -c -fPIC' -C SSMAMTtools/build/linux
  - sudo install -D SSMAMTtools/include/amt.h /usr/local/include/amt.h
  - sudo install -D SSMAMTtools/lib/linux/libamt64.a /usr/local/lib/libamt.a
  - sudo ldconfig

before_script: autoreconf -i

script: ./configure --disable-silent-rules
          CPPFLAGS="-I$PWD/nacl_sdk/pepper_43/include"
          CFLAGS="--coverage"
          CXXFLAGS="--coverage"
          LDFLAGS="-L$PWD/nacl_sdk/pepper_43/lib/glibc_x86_64 --coverage" &&
        make &&
        make check

after_success: bash <(curl -s https://codecov.io/bash)
after_failure: test -r tests/test-suite.log && cat tests/test-suite.log
